# available tags:
#   <city>
#   <icon>
#   <temperature>
#   <temperature_feels_like>
#   <temperature_max>
#   <temperature_min>
#   <pressure>
#   <humidity>
#   <wind_speed>
#   <cloud_percentage>
#   <sunrise>
#   <sunset>
# default: '<icon> <temperature>Â°C'
format = '<icon> <temperature>Â°C Feels Like: <temperature_feels_like>Â°C <city>' 
# in seconds
# if a negative interval is specified, wedder exits after printing the weather once
interval = 30

[units]
# available units:
#   Celsius
#   Fahrenheit
#   Kelvin
# default: Celsius
temperature = 'Celsius'
# available units:
#   Ms
#   Kmh
#   Mph
# default: Kmh
wind_speed = 'Mph'

[weather]
# available providers:
#   OpenWeatherMap
# default: OpenWeatherMap
provider = 'OpenWeatherMap'
# enter your API key here

[location]
# available providers:
#   IpApi
#   Manual
# default: IpApi
provider = 'IpApi'
# if you choose 'Manual' as provider, you can set your coordinates
#lat = 51.5114
#lon = 0.3180

# install one of the patched fonts from Nerd Fonts to display the icons:
# https://github.com/ryanoasis/nerd-fonts#patched-fonts
[icons]
# the icons displayed here are also the defaults
clear_sky = 'â˜‰'
few_clouds = 'ï›„'
clouds = 'â˜'
many_clouds = 'ï…'
rain_sun = 'ğŸŒ¦'
rain = 'ğŸŒ§'
heavy_rain = 'â›ˆ'
thunderstorm = 'â›ˆ'
snow = 'â›‡'
mist = 'ğŸŒ«'


